### ISSUE TITLE
The ckpt about ”latent_avg_W+_256.pt“

### ISSUE THREAD

**Issue by lijunnankman** [tflsguoyu/svbrdf-diff-renderer#4]
Halo，when I want to obtain latent_avg_W+_256.pt, dropbox prompts me that I do not have permission to obtain it. However, the acquisition of the other three ckpts is normal. How to solve it? Thanks.

**Comment by tflsguoyu** [comment]
Thank you for the feedback, and I just fixed the link. Please try it again.

**Comment by lijunnankman** [comment]
@tflsguoyu Thanks for your quick reply. I still have a question: can the code you provide currently only be used for finetune? Or how can I train myself to get the pth (materialgan.pth) you provided?

**Comment by tflsguoyu** [comment]
This code is for svbrdf reconstruction from captured photos to texture maps. 
If you want to retrain the materialGAN with your own training data, please refer to StyleGAN2. 
The only difference is the channel of input images is 9 but not 3.

**Comment by lijunnankman** [comment]
Thank you for your reply. So that means latent_avg _W+_256.pt, latent_const_N_256.pt and latent_const_W+_256.pt are all trained by StyleGAN2?
In addition, there does not seem to be any related operations to generate optim_pixel_1024.json in the code.（https://github.com/tflsguoyu/svbrdf-diff-renderer/blob/master/run.py#L37）. How can I obtain the optim_pixel_1024.json ?

**Comment by tflsguoyu** [comment]
You will get the json files by running    
`gen_targets_from_capture(material_dir, size=17.0, depth=0.1)`
in `run.py`.

`latent_avg _W+_256.pt`, `latent_const_N_256.pt` and `latent_const_W+_256.pt` are not training results. They are just the initialization of the latent vectors. If you want to regenerate them for a retrained model, you should embed the texture maps to latent vectors (W+, N) by optimization. I don't have the exact codes for that but you can use `optim_ganlatent()` as a reference.

**Comment by lijunnankman** [comment]
But only 3 json files were generated, which did not include optim_pixel_1024.json. Can you check it?

In addition, how do I understand the corresponding meanings of "const" and "avg" symbols?

Thanks！

**Comment by tflsguoyu** [comment]
I added the code to generate `optim_pixel_1024.json`. When you run `gen_targets_from_capture()`, you will get 4 json files.
For `avg` and `const`, please refer to Fig 8 in paper. `avg` is for (a) and `const` is for (b).
